{
  "comments": [
    {
      "key": {
        "uuid": "b0b57fa3_f1155bea",
        "filename": "src/biccommands.cpp",
        "patchSetId": 11
      },
      "lineNbr": 108,
      "author": {
        "id": 1000559
      },
      "writtenOn": "2021-01-04T21:56:31Z",
      "side": 1,
      "message": "Should it return failure if exception is caught?",
      "range": {
        "startLine": 107,
        "startChar": 4,
        "endLine": 108,
        "endChar": 50
      },
      "revId": "d93efe105411275d7158edac057552b1b93abcd7",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "0c2289be_e85f2592",
        "filename": "src/biccommands.cpp",
        "patchSetId": 11
      },
      "lineNbr": 108,
      "author": {
        "id": 1000546
      },
      "writtenOn": "2021-01-11T04:55:53Z",
      "side": 1,
      "message": "Yes. Thanks for your comments.\nUpdated the patchset.",
      "parentUuid": "b0b57fa3_f1155bea",
      "range": {
        "startLine": 107,
        "startChar": 4,
        "endLine": 108,
        "endChar": 50
      },
      "revId": "d93efe105411275d7158edac057552b1b93abcd7",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}